# Change these first
owner: hbwebpages # Your GitHub username
repo: halilbozdoganstatus # Your GitHub repository name

# Add your sites here
sites:
  - name: Halil Bozdogan Blog
    url: https://www.halilbozdogan.com
  - name: Halil Bozdogan CV
    url: https://cv.halilbozdogan.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /halilbozdoganstatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Halil Bozdogan Status Pages
  introTitle: "**Halil Bozdogan** Web Sites Status Pages"
  introMessage: Uptime status of my personel pages 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
